spring:
  datasource:
    url: jdbc:postgresql://dpg-d1coca7fte5s738r9b0g-a.oregon-postgres.render.com:5432/cardapio_3d6a
    username: cardapio_3d6a_user
    password: ydzKqfvG581u4jg1zT8cQVeRaz61xpCc
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
